### ISSUE TITLE
Seeds Domain

### ISSUE THREAD

**Issue by eullercristian** [codecasts/laravel#2]
Pessoal, como faço para rodar as seeds do Domain?

Desde já agradeço.

Atenciosamente

**Comment by fraterblack** [comment]
Use o pacote [Artesãos/Migrator](https://github.com/artesaos/migrator)

**Comment by eullercristian** [comment]
@fraterblack  já estou usando, qual seria o comando para executar as seeds?

**Comment by fraterblack** [comment]
php artisan migrator --seed

**Comment by eullercristian** [comment]
Deu certo @fraterblack, muito obrigado
